version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
  celery:
    build: .
    command: celery -A app.celery_worker worker --loglevel=info
    depends_on:
      - redis
volumes:
  pgdata: